// GET /api/movement?movement=home&householdId={id}
//   (or ?userId={id} — resolved to the household)
//
// Returns the live picture for one movement so the mobile movement screens can
// render an intelligence observation + next action at the top of the glass
// card:
//   { movement, activeSignals, patterns, intelligence, nextAction }
//
// The intelligence/nextAction pair is generated by Haiku from the movement's
// signals + learned patterns, cached ~30m so screen mounts don't each spend a
// model call.

import { Redis } from "@upstash/redis";
import { MOVEMENTS, signalMovement } from "./movements.js";

const redis = new Redis({
  url: process.env.UPSTASH_REDIS_REST_URL,
  token: process.env.UPSTASH_REDIS_REST_TOKEN,
});

const parse = (v) => { try { return typeof v === "string" ? JSON.parse(v) : v; } catch { return null; } };
const INTEL_TTL_S = 30 * 60;
const LABELS = { home: "Home", work: "Work", family: "Family", wellness: "Wellness" };

function isActive(s) {
  return !s.state || s.state === "incoming" || s.state === "active";
}

// Compact, model-facing view of a signal.
function shapeSignal(s) {
  return {
    id: s.id,
    description: s.description || "",
    type: s.type || "unknown",
    eta: s.eta || null,
    state: s.state || "incoming",
    sender: s.sender || null,
    movement: signalMovement(s),
  };
}

async function generateIntelligence(movement, signals, patterns) {
  const label = LABELS[movement];
  const signalLines = signals.length
    ? signals.slice(0, 15).map((s) => `- ${s.description}${s.eta ? ` (eta ${s.eta})` : ""} [${s.type}]`).join("\n")
    : "(no active signals)";
  const prompt = `You are The Conductor, a calm household intelligence. Look at the ${label} Movement for this household and respond with ONLY a JSON object:
{
  "intelligence": "one sentence — a genuine, specific observation about this movement right now; calm and grounded, never a to-do",
  "nextAction": "one short phrase — the single most important thing to address in this movement (or '' if nothing needs attention)"
}

Active ${label} signals:
${signalLines}

Learned ${label} patterns:
${JSON.stringify(patterns || {})}

Be specific to what's actually here. If the movement is quiet, say so plainly and set nextAction to "".`;

  try {
    const resp = await fetch("https://api.anthropic.com/v1/messages", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": process.env.ANTHROPIC_API_KEY,
        "anthropic-version": "2023-06-01",
      },
      body: JSON.stringify({
        model: "claude-haiku-4-5-20251001",
        max_tokens: 200,
        messages: [{ role: "user", content: prompt }],
      }),
    });
    const data = await resp.json();
    const text = data?.content?.[0]?.text || "{}";
    const clean = text.replace(/```json|```/g, "").trim();
    const obj = JSON.parse(clean);
    return {
      intelligence: typeof obj.intelligence === "string" ? obj.intelligence : "",
      nextAction: typeof obj.nextAction === "string" ? obj.nextAction : "",
    };
  } catch (err) {
    console.warn(`[movement] intelligence generation failed (${movement}):`, err?.message || err);
    // Graceful template fallback so the screen still has something to show.
    return {
      intelligence: signals.length
        ? `The ${label} Movement has ${signals.length} active signal${signals.length === 1 ? "" : "s"} right now.`
        : `The ${label} Movement is quiet right now.`,
      nextAction: signals.length ? (signals[0].description || "") : "",
    };
  }
}

export default async function handler(req, res) {
  if (req.method !== "GET") {
    return res.status(405).json({ error: "Method not allowed" });
  }
  const movement = String(req.query?.movement || "").toLowerCase();
  if (!MOVEMENTS.includes(movement)) {
    return res.status(400).json({ error: `movement must be one of ${MOVEMENTS.join(", ")}` });
  }

  // Resolve household — accept householdId directly, or a userId to look up.
  let householdId = req.query?.householdId;
  if (!householdId && req.query?.userId) {
    householdId = (await redis.get(`user:${req.query.userId}:household`)) || req.query.userId;
  }
  if (!householdId) {
    return res.status(400).json({ error: "householdId or userId required" });
  }

  try {
    const [rawSignals, patterns] = await Promise.all([
      redis.lrange(`household:${householdId}:signals`, 0, -1).catch(() => []),
      redis.get(`household:${householdId}:movement:${movement}:patterns`).catch(() => null),
    ]);
    const allSignals = (rawSignals || []).map(parse).filter(Boolean);
    const movementSignals = allSignals.filter((s) => signalMovement(s) === movement);
    const activeSignals = movementSignals.filter(isActive).map(shapeSignal);
    const parsedPatterns = parse(patterns) || {};

    // Cached intelligence — keyed by movement, refreshed when the cache
    // expires or the active-signal fingerprint changes.
    const fingerprint = activeSignals.map((s) => `${s.id}:${s.state}`).join("|");
    const intelKey = `household:${householdId}:movement:${movement}:intel`;
    const cached = parse(await redis.get(intelKey).catch(() => null));
    let intelligence, nextAction;
    if (cached && cached.fingerprint === fingerprint) {
      intelligence = cached.intelligence;
      nextAction = cached.nextAction;
    } else {
      const gen = await generateIntelligence(movement, activeSignals, parsedPatterns);
      intelligence = gen.intelligence;
      nextAction = gen.nextAction;
      try {
        await redis.set(intelKey, JSON.stringify({ intelligence, nextAction, fingerprint, computedAt: Date.now() }), { ex: INTEL_TTL_S });
      } catch { /* best-effort cache */ }
    }

    return res.status(200).json({
      movement,
      activeSignals,
      patterns: parsedPatterns,
      intelligence,
      nextAction,
    });
  } catch (err) {
    console.error("[movement] handler error:", err?.message || err);
    return res.status(500).json({ error: "Failed to load movement" });
  }
}
